import { defaultTheme } from "@b2io/ui/theme";
import "@b2io/ui/reset";
import { clsx } from "clsx";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, robotoMono.variable, defaultTheme)}>
        {children}
      </body>
    </html>
  );
}
