import { createThemeContract } from "@vanilla-extract/css";

const vars = createThemeContract({
  border: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
  },
  color: {
    accent: null,
    accentForeground: null,
    background: null,
    border: null,
    card: null,
    cardForeground: null,
    destructive: null,
    destructiveForeground: null,
    foreground: null,
    input: null,
    muted: null,
    mutedForeground: null,
    overlay: null,
    popover: null,
    popoverForeground: null,
    primary: null,
    primaryForeground: null,
    ring: null,
    secondary: null,
    secondaryForeground: null,
  },
  elevation: {
    dialog: null,
  },
  opacity: {
    background: null,
    foreground: null,
  },
  radii: {
    /* eslint-disable sort-keys */
    none: null,
    sm: null,
    default: null,
    md: null,
    lg: null,
    xl: null,
    "2xl": null,
    "3xl": null,
    full: null,
    /* eslint-enable sort-keys */
  },
  shadow: {
    /* eslint-disable sort-keys */
    sm: null,
    default: null,
    md: null,
    lg: null,
    xl: null,
    "2xl": null,
    inner: null,
    none: null,
    /* eslint-enable sort-keys */
  },
  space: {
    0: null,
    0.5: null,
    1: null,
    1.5: null,
    2: null,
    2.5: null,
    3: null,
    3.5: null,
    4: null,
    5: null,
    6: null,
    7: null,
    8: null,
    9: null,
    10: null,
    11: null,
    12: null,
    14: null,
    16: null,
    20: null,
    24: null,
    28: null,
    32: null,
    36: null,
    40: null,
    44: null,
    48: null,
    52: null,
    56: null,
    60: null,
    64: null,
    72: null,
    80: null,
    96: null,
    px: null,
  },
  text: {
    family: {
      mono: null,
      sans: null,
    },
    leading: {
      /* eslint-disable sort-keys */
      3: null,
      4: null,
      5: null,
      6: null,
      7: null,
      8: null,
      9: null,
      10: null,
      none: null,
      tight: null,
      snug: null,
      normal: null,
      relaxed: null,
      loose: null,
      /* eslint-enable sort-keys */
    },
    size: {
      /* eslint-disable sort-keys */
      xs: null,
      sm: null,
      base: null,
      lg: null,
      xl: null,
      "2xl": null,
      "3xl": null,
      "4xl": null,
      "5xl": null,
      "6xl": null,
      "7xl": null,
      "8xl": null,
      "9xl": null,
      /* eslint-enable sort-keys */
    },
    tracking: {
      /* eslint-disable sort-keys */
      tighter: null,
      tight: null,
      normal: null,
      wide: null,
      wider: null,
      widest: null,
      /* eslint-enable sort-keys */
    },
    weight: {
      /* eslint-disable sort-keys */
      thin: null,
      extralight: null,
      light: null,
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      black: null,
      /* eslint-enable sort-keys */
    },
  },
});

export { vars };
